#!/usr/local/bin/bash

PATTERN="([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])"

FILE="/usr/home/itymos/scripts/access.log"

. /etc/rc.subr

name="calc_requests"
rcvar="calc_requests_enable"


start_cmd="${name}_start"

stop_cmd=":"


calc_requests_start(){
	if [ $1 ]; then
	    echo "The number of requests to the IP $1 in the file access.log.1 located in my home directory is"
    	    # the parameter should be taken out and dots should be escaped to provide proper match!!
    	    ip_with_escapes=$(echo $1 | sed s/'\.'/'\\.'/g)
            egrep -wo "$ip_with_escapes" /usr/home/itymos/scripts/access.log | uniq -c
	else
            echo "I am starter here! "
            egrep -wo "$PATTERN" "$FILE" | uniq -c
            echo "I'm done!"
	fi
}

load_rc_config $name
run_rc_command "$@"
